### PR TITLE
Update deps

### LINKED ISSUE #2: Update WPCS
It would be nice to see how this config would fit in with WPCS 1.1.0.
They've made a lot of changes and moved sniffs around so this is a bit more complicated than looking at what was depreciated.

### PR DESCRIPTION
**Pull request by szepeviktor**
Fixes #2

@sirbrillig Please merge it.

### CODE REVIEW

**Comment by sirbrillig** [comment]
Thank you for the PR! Can you confirm there are no conflicts between the config here and the updated sniffs? I can't test it out right now because I'm on a trip for the next few weeks.

The reason I hadn't updated this until now was two-fold: I was waiting for 2.0 to be released, but also because from what I can tell a lot of the sniff codes may have changed and therefore might need to be updated here.

**Comment by szepeviktor** [comment]
@sirbrillig Oh yes!!

See https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/CHANGELOG.md

**Comment by sirbrillig** [comment]
Thank you. That looks good!

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
