### PR TITLE
Support PHP 8.0

### PR DESCRIPTION
**Pull request by szepeviktor**
@sirbrillig Please merge this one.

### CODE REVIEW

**Comment by sirbrillig** [comment]
This is a good idea, thanks! I just need to find some time to test the code with PHP 8 before I can make a release that supports it.

**Comment by szepeviktor** [comment]
I could land you a fresh @UpCloudLtd instance with PHP 8.0

**Comment by leonstafford** [comment]
@sirbrillig I try to compete with @szepeviktor's offer with a PHP 8 [Lokl](https://lokl.dev) instance you can run locally and keep free forever 😸

**Comment by szepeviktor** [comment]
@sirbrillig Friendly ping.

I'm unable to add PHP 8 support for packages depending on this one.

**Comment by sirbrillig** [comment]
Seems fine. Upgrading.

**Pull request merged**
